version: "3.9"

x-templates:
  default-service: &default-service
    restart: unless-stopped
    tty: true
    stdin_open: true
    init: true
    extra_hosts:
      - host.docker.internal:host-gateway
  as-current-user: &as-current-user
    user: ${UID:-1000}:${GID:-1000}

services:
  app:
    <<: *default-service
    <<: *as-current-user
    image: chat-room/api
    build:
      context: ..
      dockerfile: ./api/Dockerfile
    container_name: chat-room-api-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD: app
    ports:
      - "8080:8080"
  db:
    <<: *default-service
    image: postgres:14-alpine
    container_name: chat-room-api-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: chat-room-api-db-data
    driver: local
